Generated  models and request builders
microsoftgraph/msgraph-sdk-java pull request #1368
Opened 2023-03-07 13:33 UTC by andrueastman

This pull request was automatically created by Azure Pipelines. **Important** Check for unexpected deletions or changes in this PR.

2023-03-07 13:48 UTC, baywet requested changes
@andrueastman a number of things have been removed and I'm not sure whether they are expected:
1. /users : skip query param, expected
1. /groups/validateProperties? 
1. /groups/{id}/members cast to user, application, servicePrincipal, device, orgContact. I'm guessing cast to user and service principal should not have been removed?
1. /orgContacts/{id}/ cast to user, servicePrincipal, orgContact, application, device. I'm guessing this is expected.
1. /servicePrincipals/{id}/memberOf/ cast to user, application, servicePrincipal, device, orgContact. Guessing this is expected.
1. /users/{id}/memberOf/ cast to user, application, servicePrincipal, device, orgContact. Guessing this is expected.
1. /devices/{id}/memberOf/ cast to user, application, servicePrincipal, device, orgContact. Guessing this is expected.

2023-03-07 14:35 UTC, andrueastman commented on src/main/java/com/microsoft/graph/requests/GroupCollectionRequestBuilder.java
> -    public DirectoryObjectValidatePropertiesRequestBuilder validateProperties(@Nonnull final DirectoryObjectValidatePropertiesParameterSet parameters) {
This shouldn't be dropped.

2023-03-07 14:37 UTC, andrueastman commented on src/main/java/com/microsoft/graph/requests/DeviceRequestBuilder.java
> -    public com.microsoft.graph.requests.UserCollectionRequestBuilder memberOfAsUser() {
Related to fix at https://github.com/microsoftgraph/msgraph-metadata/pull/286

2023-03-07 14:44 UTC, andrueastman commented on src/main/java/com/microsoft/graph/requests/UserCollectionRequest.java
> -     * @param value of the number of items to skip
Related to fix at https://github.com/microsoftgraph/msgraph-metadata/pull/283

2023-03-08 08:00 UTC, andrueastman commented
> /groups/{id}/members cast to user, application, servicePrincipal, device, orgContact. I'm guessing cast to user and service principal should not have been removed?

I believe this is removing the `memberOf` casts for a group because a group can only be a member of another group.

2023-03-08 08:00 UTC, andrueastman commented
Closing this for now as it superceded by https://github.com/microsoftgraph/msgraph-sdk-java/pull/1371

2023-03-08 08:00 UTC, closed without merging