Support Branch Protection
microsoftgraph/msgraph-sdk-java pull request #1820
Opened 2024-02-14 20:16 UTC by ramsessanchez

Any changes that are made to the support/5.x.x branch, as unlikely as they may be, should be checked and validated.

2024-02-15 06:40 UTC, andrueastman approved these changes
👍🏼

2024-02-15 13:16 UTC, baywet requested changes

2024-02-15 13:16 UTC, baywet commented on .github/policies/msgraph-sdk-java-branch-protection.yml
> +    - build
same comment about updating the workflows to trigger on push/PR to that branch

2024-02-15 20:17 UTC, baywet approved these changes

2024-02-19 14:48 UTC, baywet approved these changes

2024-02-20 04:33 UTC, merged