If an error is available during upload report this in the ClientExcep…
microsoftgraph/msgraph-sdk-java pull request #671
Opened 2021-02-19 13:51 UTC by AllenConquest

During testing of the ChunkedUploadProvider.upload() method, an error in the callback was being created. However, this error is being swallowed by the ChunkedUploadRequest class, and not reported back through the exception handling. This change is to pass the original error back to the calling code. This would be much more helpful in debugging errors occurring in the callback handling.

2021-02-19 13:58 UTC, baywet requested changes
Thank you so much for your feedback and your contribution!
A minor comment here.

2021-02-19 13:58 UTC, baywet commented on src/main/java/com/microsoft/graph/requests/extensions/ChunkedUploadRequest.java
> +                new ClientException("Upload session failed.", result != null ? result.getError() : null));
```suggestion
                new ClientException("Upload session failed.", result == null ? null : result.getError()));
```
nit: readability

2021-02-19 13:59 UTC, baywet approved these changes
additional review after implementing the minor change.

2021-02-19 14:52 UTC, andrueastman approved these changes
👍

2021-02-19 15:56 UTC, merged

2021-02-19 15:57 UTC, baywet commented
@AllenConquest your contribution will go out with version 2.9.0 which should go out next week. Thanks!

2021-02-19 17:26 UTC, AllenConquest commented
Thanks for the speedy update. However, I now have an issue trying to upgrade from 2.3.1 to 2.8.1. I will raise a separate issue.

2021-02-26 13:14 UTC, AllenConquest commented
Do you have any idea when version 2.9.0 will be release?

2021-02-26 13:19 UTC, baywet commented
the plan was to have it released this week. But the service didn't release any update so we decided not to release to save people from an upgrade. I'm tracking the target date [here](https://github.com/microsoftgraph/msgraph-sdk-java/milestone/15)